  # Название процесса, которое будет отображаться в GitHub Actions
name: Deploy to Firebase Hosting

# Триггер: запускать этот процесс при каждом push в ветку 'main'
on:
  push:
    branches:
      - main

jobs:
  # Название задачи
  deploy_to_firebase:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 1. Шаг: Скачиваем исходный код вашего репозитория
      - uses: actions/checkout@v3

      # 2. Шаг: Разворачиваем сайт на Firebase Hosting (ИСПОЛЬЗУЕМ НОВУЮ ВЕРСИЮ)
      - uses: FirebaseExtended/action-hosting-deploy@v0.9.1 # <--- ВОТ ГЛАВНОЕ ИЗМЕНЕНИЕ!
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # Используем секрет с токеном, как и планировали
          firebaseToken: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          # ID вашего проекта
          projectId: 'razrabotka-b61bc'
