    # Название процесса
name: Deploy to Firebase Hosting

# Триггер на push в ветку main
on:
  push:
    branches:
      - main

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код
      - uses: actions/checkout@v3

      # 2. Разворачиваем сайт
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAZRABOTKA }}'
          channelId: live  # <--- ВОТ ЭТА СТРОКА РЕШИТ ПРОБЛЕМУ
          projectId: 'razrabotka-b61bc'
